import type { PlanTask } from "./types";

/** Curated tasks for scoring — extend with new objects as needed */
export const PLAN_TASK_LIBRARY: PlanTask[] = [
  {
    id: "sch-1",
    name: "Review lecture notes (30 min)",
    type: "school",
    difficulty: "easy",
    hasDeadline: false,
  },
  {
    id: "sch-2",
    name: "Finish problem set draft",
    type: "school",
    difficulty: "hard",
    hasDeadline: true,
  },
  {
    id: "sch-3",
    name: "Read assigned chapter",
    type: "school",
    difficulty: "medium",
    hasDeadline: false,
  },
  {
    id: "sch-4",
    name: "Email professor question",
    type: "school",
    difficulty: "easy",
    hasDeadline: true,
  },
  {
    id: "ten-1",
    name: "Serve practice bucket (20 min)",
    type: "tennis",
    difficulty: "medium",
    hasDeadline: false,
  },
  {
    id: "ten-2",
    name: "Footwork ladder drills",
    type: "tennis",
    difficulty: "easy",
    hasDeadline: false,
  },
  {
    id: "ten-3",
    name: "Match play simulation",
    type: "tennis",
    difficulty: "hard",
    hasDeadline: false,
  },
  {
    id: "gen-1",
    name: "Inbox zero (email)",
    type: "general",
    difficulty: "easy",
    hasDeadline: false,
  },
  {
    id: "gen-2",
    name: "Plan tomorrow’s top 3",
    type: "general",
    difficulty: "easy",
    hasDeadline: false,
  },
  {
    id: "gen-3",
    name: "Deep work block — one project",
    type: "general",
    difficulty: "hard",
    hasDeadline: false,
  },
  {
    id: "wrk-1",
    name: "Sync with team on blockers",
    type: "work",
    difficulty: "medium",
    hasDeadline: true,
  },
  {
    id: "wrk-2",
    name: "Write status update",
    type: "work",
    difficulty: "easy",
    hasDeadline: true,
  },
  {
    id: "hlth-1",
    name: "Stretch + mobility (15 min)",
    type: "health",
    difficulty: "easy",
    hasDeadline: false,
  },
  {
    id: "hlth-2",
    name: "Walk outside (20 min)",
    type: "health",
    difficulty: "easy",
    hasDeadline: false,
  },
  {
    id: "art-1",
    name: "Sketch / creative warm-up",
    type: "creative",
    difficulty: "easy",
    hasDeadline: false,
  },
];
